### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by avighi** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#1]
deepstream_test5_app_main.c: In function ‘bbox_generated_probe_after_analytics’:
deepstream_test5_app_main.c:438:25: error: ‘NvDsConfig {aka struct <anonymous>}’ has no member named ‘dsanalytics_config’; did you mean ‘dsexample_config’?
     if (!appCtx->config.dsanalytics_config.enable){
                         ^~~~~~~~~~~~~~~~~~
                         dsexample_config
deepstream_test5_app_main.c: In function ‘event_thread_func’:
deepstream_test5_app_main.c:756:19: error: ‘AppCtx {aka struct _AppCtx}’ has no member named ‘active_source_index’
       appCtx[rcfg]->active_source_index = source_id;
                   ^~
deepstream_test5_app_main.c:804:15: error: ‘AppCtx {aka struct _AppCtx}’ has no member named ‘active_source_index’
   appCtx[rcfg]->active_source_index = -1;
               ^~
deepstream_test5_app_main.c: In function ‘nvds_x_event_thread’:
deepstream_test5_app_main.c:867:18: error: ‘AppCtx {aka struct _AppCtx}’ has no member named ‘active_source_index’
     appCtx[index]->active_source_index = source_id;
                  ^~
deepstream_test5_app_main.c:874:21: error: ‘AppCtx {aka struct _AppCtx}’ has no member named ‘active_source_index’
        appCtx[index]->active_source_index = -1;
                     ^~
deepstream_test5_app_main.c: In function ‘main’:
deepstream_test5_app_main.c:998:11: error: ‘AppCtx {aka struct _AppCtx}’ has no member named ‘active_source_index’
  appCtx[i]->active_source_index = -1;
           ^~
Makefile:66: recipe for target 'deepstream_test5_app_main.o' failed
make: *** [deepstream_test5_app_main.o] Error 1

How can I do?

**Comment by monjha** [comment]
Hi,
Which deepstream version are you using?

**Comment by avighi** [comment]
5.0

**Comment by monjha** [comment]
Seems like you don't have dsanalytics_config added in NvDsConfig. Could you please check   NvDsDsAnalyticsConfig dsanalytics_config; in NvDsconfig at sources/apps/sample_apps/deepstream-app/deepstream_app.h?
