### ISSUE TITLE
Unable to run the application 

### ISSUE THREAD

**Issue by gigwegbe** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#11]
I ran the command .`/deepstream_test5 -c configs/test5_config_file_src_infer_tlt.txt`
I got: `bash: ./deepstream_test5: No such file or directory`
How can we resolve the above? Thanks

**Comment by ACAVJW4H** [comment]
Did you follow the commands and build the executable?

**Comment by gigwegbe** [comment]
Resolved. Thanks

**Comment by gigwegbe** [comment]
Update: It correct command is `./deepstream_test5 -c config/test5_config_file_src_infer_tlt.txt` not `./deepstream_test5 -c configs/test5_config_file_src_infer_tlt.txt`

**Comment by monjha** [comment]
Thank you for pointing that out. I have updated the command.
