### ISSUE TITLE
Error while executing "sudo make"

### ISSUE THREAD

**Issue by MIMNSI** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#15]
I modified my makefile according to the answer given here, to accommodate Deepstream 5.1:

https://forums.developer.nvidia.com/t/fatal-error-cuda-runtime-api-h-no-such-file-or-directory-when-compiling-with-jetpack-4-5-1/171218/8

However, now I'm getting another error:
deepstream_test5_app_main.c:41:10: fatal error: deepstream_app.h: No such file or directory
 #include "deepstream_app.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:69: recipe for target 'deepstream_test5_app_main.o' failed
make: *** [deepstream_test5_app_main.o] Error 1

Using Deepstream SDK 5.1, CUDA 10.2, Jetson AGX Xavier

**Comment by monjha** [comment]
Hi ,

I have updated the Makefile for DS5.1.
