### ISSUE TITLE
what do I have to do at this step ? 

### ISSUE THREAD

**Issue by MuhammedRishdhi123** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#18]
For Jetson use: bin/jetson/libnvds_msgconv.so
For x86 use: bin/x86/libnvds_msgconv.so
I am using a jetson nano

**Comment by LashaKharshiladze-Zoetis** [comment]
Put it in  test5_config_file_src_infer_tlt.txt  find line which starts with  (in original config line 103)  "msg-broker-proto-lib="

**Comment by xarshila** [comment]
Put it in test5_config_file_src_infer_tlt.txt find line which starts with (in original config line 103) "msg-broker-proto-lib="
