### ISSUE TITLE
How do I use the webcam as the input stream ?

### ISSUE THREAD

**Issue by MuhammedRishdhi123** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#19]
I tried changing the source type to camera v4l2 but afterwards when I run the app it displays the following error :
create camera source bin failed
Is there anywhere else I should adjust in order for this change to takesplace.
@monjha

**Comment by mjhuria** [comment]
What type of camera are you using? what updates did you make in the config file?

**Comment by MuhammedRishdhi123** [comment]
I used a logitech c270 webcam in a jetson nano 4GB version
I changed the source to  type 1 in the config however I figured out the issue I haven't set the camera parameters in the config like the fps and the height after updating them it worked. Thanks for the reply !
