### ISSUE TITLE
Is there a python version of this app ?

### ISSUE THREAD

**Issue by John-devo** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#20]
Would appreciate it ! @monjha

**Comment by mjhuria** [comment]
Hi John-devo,

Currently the python version is not available

**Comment by MuhammedRishdhi123** [comment]
> Hi John-devo,
> 
> Currently the python version is not available

Is it possible to do the same functionality in python in deepstream 5.0 ?

**Comment by monjha** [comment]
Hi,

yes, you can do that. you can refer analytics application: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-nvdsanalytics
and deepstream-test4 application: https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-test4

**Comment by MuhammedRishdhi123** [comment]
Thanks it was helpful !

**Comment by bug-developer021** [comment]
@John-devo  I build a custom python version to support send analytics data based on deepstream-6.1 , it may help you.

https://github.com/bug-developer021/deepstream_python_nvdsanalytics_to_kafka
