### ISSUE TITLE
How can I add overcrowding plugin also to this app? 

### ISSUE THREAD

**Issue by MuhammedRishdhi123** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#21]
I want to add the overcrowding plugin also to this app and send the data using kafka so where should I make the alterations. Thanks in advance !

**Comment by monjha** [comment]
Hi,

You can do that by adding overcrowding in configuration. So,
1. enable https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/blob/f55511dd59f79eb23f96be372b731bb16172f201/config/config_nvdsanalytics.txt#L60
2. access overcrowding data indeepstream_nvdsanalytics_meta.cpp and also add the overcrowding in msgconv. 
3. update deepstream_test5_app_main.c and the overcrowding in event message meta.
4. build the msgconv and run the application.
Please check the webinar content on how to update the sources.

Thank you!

**Comment by MuhammedRishdhi123** [comment]
Thanks it worked !
