### ISSUE TITLE
cuda_runtime_api.h not found

### ISSUE THREAD

**Issue by axelthegr8** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#22]
Hello. I have been trying for a long time to get past this error but can't make it work. I have tried updating the path and much more. But nothing seems to get it to understand where to find the cuda_runtime_api.h. Eventhough I know it's present where it should be. 

```
cc -c -o ../../apps-common/src/deepstream_source_bin.o  -DPLATFORM_TEGRA -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../../apps-common/src/deepstream_source_bin.c
../../apps-common/src/deepstream_source_bin.c:32:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:66: recipe for target '../../apps-common/src/deepstream_source_bin.o' failed
make: *** [../../apps-common/src/deepstream_source_bin.o] Error 1
```

**Comment by axelthegr8** [comment]
Must have had a typo. Retried a solution with some changes in the Makefile. And this time it worked. 
Change of value to: 
`-DDS_VERSION_MINOR=1`
In line:
`CFLAGS+= -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=5`
Added lines: 
```
CFLAGS+= -I/usr/local/cuda-10.2/include
LIBS+= -L/usr/local/cuda-10.2/lib64/ -lcudart -lcuda
```

Cut out from the Makerfile with the corrected code:
```
CFLAGS+= -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5
CFLAGS+= -I$(INC_DIR)
CFLAGS+= -I/usr/local/cuda-10.2/include

LIBS+= -L$(LIB_INSTALL_DIR) -lnvdsgst_meta -lnvds_meta -lnvdsgst_helper -lnvdsgst_smartrecord -lnvds_utils -lnvds_msgbroker -lm \
       -lgstrtspserver-1.0 -ldl -Wl,-rpath,$(LIB_INSTALL_DIR)
LIBS+= -L/usr/local/cuda-10.2/lib64/ -lcudart -lcuda
```

Instructions came from this: https://forums.developer.nvidia.com/t/fatal-error-cuda-runtime-api-h-no-such-file-or-directory-when-compiling-with-jetpack-4-5-1/171218

**Comment by monjha** [comment]
Thank you for pointing that out. Updated the Makefile to reflect DS version 5.1.
