### ISSUE TITLE
Counter in kafka not updating

### ISSUE THREAD

**Issue by zenor87** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#23]
The entry, exit and occupancy count is always 0 in the kafka message output. I am running a video in loop for my testing.

My kafka message output is slightly different from the expected.

{
  "messageid" : "0bf31cbb-5254-488f-8588-af1007a495c4",
  "@timestamp" : "2021-05-06T08:58:39.166Z",
  "analyticsModule" : {
    "occupancy" : 0.0,
    "source_id" : 0.0,
    "Entry" : 0.0,
    "Exit" : 0.0
  },
  "videoPath" : ""
}

Did I miss some configuration or did something wrong?

**Comment by monjha** [comment]
are you using the libnvds_msgconv.so from the repo? could you please share the log?

**Comment by zenor87** [comment]
hi, I did a fresh install of the setup again and it's working. I think the issue might possibly due to the wrong kafka version type being used, used a non-scala version initially.
