### ISSUE TITLE
make errors while build

### ISSUE THREAD

**Issue by NeeSim** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#25]
I am getting the following error while doing make inside the docker container, can some one please help.

root@2d52ce7ae06c:/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics# CUDA_VER=11.1 make
g++ -o deepstream-test5-analytics deepstream_test5_app_main.o ../deepstream-test5/deepstream_utc.o ../deepstream-app/deepstream_app.o ../deepstream-app/deepstream_app_config_parser.o ../../apps-common/src/deepstream_tracker_bin.o ../../apps-common/src/deepstream_primary_gie_bin.o ../../apps-common/src/deepstream_source_bin.o ../../apps-common/src/deepstream_c2d_msg.o ../../apps-common/src/deepstream_config_file_parser.o ../../apps-common/src/deepstream_common.o ../../apps-common/src/deepstream_sink_bin.o ../../apps-common/src/deepstream_perf.o ../../apps-common/src/deepstream_dewarper_bin.o ../../apps-common/src/deepstream_dsexample.o ../../apps-common/src/deepstream_secondary_gie_bin.o ../../apps-common/src/deepstream_dsanalytics.o ../../apps-common/src/deepstream_tiled_display_bin.o ../../apps-common/src/deepstream_c2d_msg_util.o ../../apps-common/src/deepstream_osd_bin.o ../../apps-common/src/deepstream_streammux.o deepstream_nvdsanalytics_meta.o -L/opt/nvidia/deepstream/deepstream-5.1/lib/ -lnvdsgst_meta -lnvds_meta -lnvdsgst_helper -lnvdsgst_smartrecord -lnvds_utils -lnvds_msgbroker -lm -lgstrtspserver-1.0 -ldl -Wl,-rpath,/opt/nvidia/deepstream/deepstream-5.1/lib/ `pkg-config --libs gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0`
/usr/bin/ld: cannot find -lnvdsgst_meta
/usr/bin/ld: cannot find -lnvds_meta
/usr/bin/ld: cannot find -lnvdsgst_helper
/usr/bin/ld: cannot find -lnvdsgst_smartrecord
/usr/bin/ld: cannot find -lnvds_utils
/usr/bin/ld: cannot find -lnvds_msgbroker
collect2: error: ld returned 1 exit status
Makefile:69: recipe for target 'deepstream-test5-analytics' failed
make: *** [deepstream-test5-analytics] Error 1

My device information
Hardware Platform(x86 with RTX 3080)
Deepstream Version(Deepstream5.0 using Docker image nvcr.io/nvidia/deepstream:5.0-20.07-triton)

Also what should I do with the following, instructions are not clear 
For x86 use: bin/x86/libnvds_msgconv.so
Should I run it like this export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:bin/x86/libnvds_msgconv.so

**Comment by monjha** [comment]
Hi,

Please use deepsteam 5.1 container.

**Comment by BaoLee2589** [comment]
> I am getting the following error while doing make inside the docker container, can some one please help.
> 
> root@2d52ce7ae06c:/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics# CUDA_VER=11.1 make
> g++ -o deepstream-test5-analytics deepstream_test5_app_main.o ../deepstream-test5/deepstream_utc.o ../deepstream-app/deepstream_app.o ../deepstream-app/deepstream_app_config_parser.o ../../apps-common/src/deepstream_tracker_bin.o ../../apps-common/src/deepstream_primary_gie_bin.o ../../apps-common/src/deepstream_source_bin.o ../../apps-common/src/deepstream_c2d_msg.o ../../apps-common/src/deepstream_config_file_parser.o ../../apps-common/src/deepstream_common.o ../../apps-common/src/deepstream_sink_bin.o ../../apps-common/src/deepstream_perf.o ../../apps-common/src/deepstream_dewarper_bin.o ../../apps-common/src/deepstream_dsexample.o ../../apps-common/src/deepstream_secondary_gie_bin.o ../../apps-common/src/deepstream_dsanalytics.o ../../apps-common/src/deepstream_tiled_display_bin.o ../../apps-common/src/deepstream_c2d_msg_util.o ../../apps-common/src/deepstream_osd_bin.o ../../apps-common/src/deepstream_streammux.o deepstream_nvdsanalytics_meta.o -L/opt/nvidia/deepstream/deepstream-5.1/lib/ -lnvdsgst_meta -lnvds_meta -lnvdsgst_helper -lnvdsgst_smartrecord -lnvds_utils -lnvds_msgbroker -lm -lgstrtspserver-1.0 -ldl -Wl,-rpath,/opt/nvidia/deepstream/deepstream-5.1/lib/ `pkg-config --libs gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0`
> /usr/bin/ld: cannot find -lnvdsgst_meta
> /usr/bin/ld: cannot find -lnvds_meta
> /usr/bin/ld: cannot find -lnvdsgst_helper
> /usr/bin/ld: cannot find -lnvdsgst_smartrecord
> /usr/bin/ld: cannot find -lnvds_utils
> /usr/bin/ld: cannot find -lnvds_msgbroker
> collect2: error: ld returned 1 exit status
> Makefile:69: recipe for target 'deepstream-test5-analytics' failed
> make: *** [deepstream-test5-analytics] Error 1
> 
> My device information
> Hardware Platform(x86 with RTX 3080)
> Deepstream Version(Deepstream5.0 using Docker image nvcr.io/nvidia/deepstream:5.0-20.07-triton)
> 
> Also what should I do with the following, instructions are not clear
> For x86 use: bin/x86/libnvds_msgconv.so
> Should I run it like this export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:bin/x86/libnvds_msgconv.so

You can also change the Makefile .If your version of  deepstream is  5.0, you can change the NVDS_VERSION:=5.1 to  5.0.

**Comment by NeeSim** [comment]
Thank you. 
When I changed docker container to 5.1 with image nvcr.io/nvidia/deepstream:5.1-21.02-devel, I get the following error during build -
_root@44a38533ab62:/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-occupancy-analytics# make
cc -c -o deepstream_test5_app_main.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` deepstream_test5_app_main.c
cc -c -o ../deepstream-test5/deepstream_utc.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../deepstream-test5/deepstream_utc.c
cc -c -o ../deepstream-app/deepstream_app.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../deepstream-app/deepstream_app.c
cc -c -o ../deepstream-app/deepstream_app_config_parser.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../deepstream-app/deepstream_app_config_parser.c
cc -c -o ../../apps-common/src/deepstream_tracker_bin.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../../apps-common/src/deepstream_tracker_bin.c
cc -c -o ../../apps-common/src/deepstream_primary_gie_bin.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../../apps-common/src/deepstream_primary_gie_bin.c
cc -c -o ../../apps-common/src/deepstream_source_bin.o  -I../../apps-common/includes -I./includes -I../../../includes -I../deepstream-app/ -DDS_VERSION_MINOR=1 -DDS_VERSION_MAJOR=5 -I../deepstream-test5 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11 json-glib-1.0` ../../apps-common/src/deepstream_source_bin.c
../../apps-common/src/deepstream_source_bin.c:32:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:66: recipe for target '../../apps-common/src/deepstream_source_bin.o' failed
make: *** [../../apps-common/src/deepstream_source_bin.o] Error 1_

Without changing the docker container, when I just change NVDS_VERSION in Makefile from 5.1 to 5.0, I am able to successfully build the app but while running I get the following Kafka related error -
_root@2d52ce7ae06c:/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics# ./deepstream-test5-analytics -c config/test5_config_file_src_infer_tlt.txt

(deepstream-test5-analytics:12634): GLib-CRITICAL **: 06:44:46.798: g_strchug: assertion 'string != NULL' failed

(deepstream-test5-analytics:12634): GLib-CRITICAL **: 06:44:46.798: g_strchomp: assertion 'string != NULL' failed
** WARN: <create_pipeline:1143>: Num of Tiles less than number of sources, readjusting to 2 rows, 1 columns
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_nvdcf.so
gstnvtracker: Batch processing is OFF
gstnvtracker: Past frame output is OFF
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:1523 Deserialize engine failed because file path: /opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics/config/peoplenet/resnet34_peoplenet_pruned.etlt_b1_gpu0_int8.engine open error
0:02:51.631861858 12634 0x5605bff48590 WARN                 nvinfer gstnvinfer.cpp:616:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1690> [UID = 1]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics/config/peoplenet/resnet34_peoplenet_pruned.etlt_b1_gpu0_int8.engine failed
0:02:51.631880052 12634 0x5605bff48590 WARN                 nvinfer gstnvinfer.cpp:616:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1797> [UID = 1]: deserialize backend context from engine from file :/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics/config/peoplenet/resnet34_peoplenet_pruned.etlt_b1_gpu0_int8.engine failed, try rebuild
0:02:51.631886347 12634 0x5605bff48590 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1715> [UID = 1]: Trying to create engine from model files
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:744 INT8 not supported by platform. Trying FP16 mode.
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:759 FP16 not supported by platform. Using FP32 mode.
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:1277 INT8 not supported by platform. Trying FP16 mode.
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:1291 FP16 not supported by platform. Using FP32 mode.
%3|1620629686.895|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Receive failed: Disconnected
%3|1620629686.895|ERROR|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Receive failed: Disconnected
%3|1620629687.082|FAIL|rdkafka#producer-1| [thrd:2d52ce7ae06c:9092/0]: 2d52ce7ae06c:9092/0: Receive failed: Disconnected
%3|1620629687.082|ERROR|rdkafka#producer-1| [thrd:2d52ce7ae06c:9092/0]: 2d52ce7ae06c:9092/0: Receive failed: Disconnected_

Kafka & zookeeper are running, I have created the quickstart-events topic. Listening to consumer at localhost:9092
Any pointers would help.

**Comment by monjha** [comment]
Hi,

could you please try with these modification mentioned in this comment: https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/issues/22#issuecomment-830392562

**Comment by monjha** [comment]
The app will work on dGPU and Jetson. We don't support the devel version of the jetson docker. 
For the issue, could you please verify if the Kafka server is running before running the app? or you see any error there?

Thanks!

**Comment by NeeSim** [comment]
Kafka is running without any errors. Looks like other are also getting same error
https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/issues/5#issuecomment-834061292

**Comment by NeeSim** [comment]
Kafka error is resolved. config/test5_config_file_src_infer_tlt.txt needs to be updated to point to right kafka library path.
Replace all 5.0 references to 5.1

**Comment by monjha** [comment]
f87bb73af72b2e46b4e8dfc0d692973002117a91

**Comment by PareshKamble** [comment]
Hi,
Getting the same error.
Won't it run on dGPU for DeepStream 6.0?
