### ISSUE TITLE
Random analytics metadata output when using a custom yolov3 model

### ISSUE THREAD

**Issue by xxl007** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#3]
Hello,

when using a yolov3 model with this application, random analytics metadata is generated by the message converter. 

I have used the provided /bin/jetson/libnvds_msgconv.so. I have also tried with a custom nvmsgconv.cpp that adds objInROIcnt["RF"], objLCCumCnt["Entry"] and objLCCumCnt["Exit"] to the output. 

The "Entry" count stays constant to 0, while the ROI "RF" and the "Exit" counts are random high numbers.

However, the analytics metadata text overlayed to the video output corresponds to the actual count.

Could it be that this application needs to be adapted to work with Yolo models?

Hardware: Jetson Xavier NX with Jetpack4.4 and Deepstream 5.0

**Comment by mjhuria** [comment]
Hi for Entry count, please update [class_id](https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/blob/5c967c89db4405fc64b2bffe5942819ae076bcf2/config/config_nvdsanalytics.txt#L72) to the class id you have in yolov3 model.

**Comment by xxl007** [comment]
Hi thanks. I have tried with both class-id=0 (since I use a single class yolo model) and even class-id=-1 (count any classes). It didn't resolve the issue, unfortunately.

**Comment by mjhuria** [comment]
Hi,
I will need to reproduce the issue Could you please share the configuration files and model files?

**Comment by monjha** [comment]
No further details on the bug so closing for now.
