### ISSUE TITLE
output type

### ISSUE THREAD

**Issue by vuminhduc97** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#31]
hello, why 's my output look like:

"analyticsModule" : {
    "id" : "XYZ",
    "description" : "",
    "source" : "OpenALR",
    "version" : "1.0",
    "confidence" : 0.0
  },
  "object" : {
    "id" : "0",
    "speed" : 0.0,
    "direction" : 0.0,
    "orientation" : 0.0,
    "person" : {
      "age" : 0,
      "gender" : "",
      "hair" : "",
      "cap" : "",
      "apparel" : "",
      "confidence" : 1.0
    },
    "bbox" : {
      "topleftx" : 0,
      "toplefty" : 0,
      "bottomrightx" : 0,
      "bottomrighty" : 0
    },
    "location" : {
      "lat" : 0.0,
      "lon" : 0.0,
      "alt" : 0.0
    },
    "coordinate" : {
      "x" : 0.0,
      "y" : 0.0,
      "z" : 0.0
    }
  },
  "event" : {
    "id" : "60938ebc-95e5-434a-a53c-6c3d15a6476e",
    "type" : "entry"
  },
  "videoPath" : ""

**Comment by mjhuria** [comment]
Hi,

You didn't update the libnvds_msgconv.so lib from https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/tree/master/bin

**Comment by vuminhduc97** [comment]
thanks for your rep, how can i build my libnvds_msgconv.so lib by myself?

**Comment by vuminhduc97** [comment]
thank u very much
