### ISSUE TITLE
No custom msgconv config file

### ISSUE THREAD

**Issue by Foglia-m** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#37]
Hi, I don't think you provide the dstest5_msgconv_sample_config.txt file you used in the example as there is no such element as entry and exit when I run your example:
 the file provided in the repo can't be the same as the one that creates the displayed logs in the gif ( no entry / exit and count such as those displayed in your example).
My logs look like the following:
`"messageid" : "d61a8342-c60c-43d9-9fbb-c62b1fe2a749",
  "mdsversion" : "1.0",
  "@timestamp" : "1970-01-01T00:00:00.000Z",
  "place" : {
    "id" : "0",
    "name" : "HWY_20_AND_LOCUST__EBA",
    "type" : "intersection/road",
    "location" : {
      "lat" : 30.32,
      "lon" : -40.549999999999997,
      "alt" : 100.0
    },
    "entrance" : {
      "name" : "C_127_158",
      "lane" : "Lane 1",
      "level" : "P1",
      "coordinate" : {
        "x" : 1.0,
        "y" : 2.0,
        "z" : 3.0
      }
    }
  },
  "sensor" : {
    "id" : "HWY_20_AND_LOCUST__EBA__4_11_2018_4_59_59_508_AM_UTC-07_00",
    "type" : "Camera",
    "description" : "Aisle Camera",
    "location" : {
      "lat" : 45.293701446999997,
      "lon" : -75.830391449900006,
      "alt" : 48.155747933800001
    },
    "coordinate" : {
      "x" : 5.2000000000000002,
      "y" : 10.1,
      "z" : 11.199999999999999
    }
  },
  "analyticsModule" : {
    "id" : "XYZ",
    "description" : "",
    "source" : "OpenALR",
    "version" : "1.0"
  },`

Can you give me a bit more insight on that difference if there are elements I didn't understand? 
Thank you

**Comment by monjha** [comment]
Hi Foglia,

Did you update the bin file: libnvds_msgconv.so?

**Comment by Foglia-m** [comment]
Ok thank you so much,  you guys did such a great job, I can thank you enough.
