### ISSUE TITLE
libnvds_msgconv.so: invalid ELF header

### ISSUE THREAD

**Issue by lguaman** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#41]
Hi,

I have installed DS6.0, kafka in dGPU and Jetson Xavier. Original DS6.0 deepstream-test5-app is running ok with Kafka enabled.
I have replaced libnvds_msgconv.so at /opt/nvidia/deepstream/deepstream-6.0/lib

When I run ds_6.0 branch: 
/opt/nvidia/deepstream/deepstream-6.0/sources/apps/sample_apps/deepstream-occupancy-analytics# ./deepstream-test5-analytics -c config/test5_config_file_src_infer_tlt.txt

It fails with the following errror message:

(deepstream-test5-analytics:374): GStreamer-WARNING **: 03:54:55.947: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_msgconv.so': ///opt/nvidia/deepstream/deepstream-6.0/lib/libnvds_msgconv.so: invalid ELF header
** ERROR: <create_msg_conv_broker_bin:234>: Failed to create 'sink_sub_bin_transform2'
** ERROR: <create_msg_conv_broker_bin:278>: create_msg_conv_broker_bin failed
** ERROR: <create_sink_bin:781>: create_sink_bin failed
** ERROR: <create_processing_instance:815>: create_processing_instance failed
** ERROR: <create_pipeline:1323>: create_pipeline failed
** ERROR: <main:1041>: Failed to create pipeline
Quitting
App run failed

Any help? 
Thanks in advance

**Comment by monjha** [comment]
Hi Is it same on both x86 and Jetson?

**Comment by lguaman** [comment]
Yes, it is, same error message

**Comment by monjha** [comment]
Thank you for confirming, I will check and get back.

**Comment by lguaman** [comment]
awesome! thanks

**Comment by monjha** [comment]
Hi please check the bin now!

Thank you!

**Comment by lguaman** [comment]
Yes, it is working now. Thanks

**Comment by lguaman** [comment]
Hi Monjha,
The message broker payload is not transmitting the Count, Entry and Exit
variables anymore, we are receiving the standard deepstream-app payload.
Can you please fix it?
Thanks

**Comment by monjha** [comment]
Hi,
It should be sending exit, entry, occupancy data. could you please add the log here?

**Comment by lguaman** [comment]
It shows entry, exit and occupancy payload, however it never increase the
objects counted and showed in the display as you can see in the image below
Attach the log too

**Comment by lguaman** [comment]
Yes, I am.
The problem is:
Persons are detected(Entry/Exit) and showed in the display by
deepstream-test5-analitycs c program, however they are not send to the
broker, I mean Entry, Exit and Occupancy ALWAYS come to Kafka as 0.0
"analyticsModule" : {
"id": "XYZ",
"description": "",
"source" : "OpenALR",
"version" : "1.0",
"Entry" : 0.0,
"Exit" : 0.0,
"Occupancy" : 0.0
}
In version for DS_5.0 It sends the message payload ok to the brocker.
How can I receive the Exit, Entry and Occupancy variables in Kafka when
they change?

**Comment by monjha** [comment]
Can you try again? Fixed the header issue for ds6.0.

**Comment by lguaman** [comment]
However, for Jetson Entry and Exit vars print changed out. Occupancy print
right.
Look attached image

**Comment by monjha** [comment]
Please try now!

**Comment by lguaman** [comment]
Yes, it works.
