### ISSUE TITLE
ERROR from sink_sub_bin_sink2: Could not initialize supporting library.

### ISSUE THREAD

**Issue by lwzhaojun** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#43]
Hello, when I run the program, the error is reported as follows, it seems that a certain library is not imported. Please help me. My configuration environment is: deepstream5.1
jetson nx
`mec@mec-desktop:/opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-occupancy-analytics-master$ ./deepstream-test5-analytics -c config/test5_config_file_src_infer_tlt.txt

(deepstream-test5-analytics:10968): GLib-CRITICAL **: 19:47:45.962: g_strchug: assertion 'string != NULL' failed

(deepstream-test5-analytics:10968): GLib-CRITICAL **: 19:47:45.963: g_strchomp: assertion 'string != NULL' failed
** WARN: <create_pipeline:1141>: Num of Tiles less than number of sources, readjusting to 2 rows, 1 columns
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
** ERROR: <main:1088>: Failed to set pipeline to PAUSED
Quitting
ERROR from sink_sub_bin_sink2: Could not initialize supporting library.
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(359): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
unable to open shared library
ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
Failed to start
App run failed
`

**Comment by monjha** [comment]
Hi,
is the kafka running on your server?

**Comment by lwzhaojun** [comment]
Thanks, I turned off Kafka.
