### ISSUE TITLE
unable to run deepstream-test5-analytics

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#5]
HI 
I'm trying to run the following command _**sudo ./deepstream-test5-analytics -c config/test5_config_file_src_infer_tlt.txt**_ under this path _**/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics**_

However, I got an error like this: 

** WARN: <create_pipeline:1143>: Num of Tiles less than number of sources, readjusting to 2 rows, 1 columns
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
** ERROR: <main:1088>: Failed to set pipeline to PAUSED
Quitting
ERROR from sink_sub_bin_sink2: Could not configure supporting library.
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(388): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
unable to connect to broker library
ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
Failed to start
App run failed

Does anyone know what would be the possible root cause?  
Thanks in advance.

**Comment by mjhuria** [comment]
The issue seems to be this: _unable to connect to broker library_
I think your configuration for sink2 is not correct. Please check :
1. msg-broker-proto-lib path and see if the .so file is there
2. Please check your setting for msg-broker-conn-str. check if you are using correct port .

**Comment by Ryan-ZL-Lin** [comment]
Hi @mjhuria 
I tried to change the .so file from ### `/opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_kafka_proto`.so 
to `/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics/bin/jetson/libnvds_msgconv.so` since I'm using Jetson nano

I also checked the msg-broker-conn-str, it's `localhost;9092;quickstart-events` as default.

and I got different error like this 

```
(deepstream-test5-analytics:16104): GLib-CRITICAL **: 18:47:12.146: g_strchug: assertion 'string != NULL' failed

(deepstream-test5-analytics:16104): GLib-CRITICAL **: 18:47:12.146: g_strchomp: assertion 'string != NULL' failed
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
** ERROR: <main:1088>: Failed to set pipeline to PAUSED
Quitting
ERROR from sink_sub_bin_sink2: GStreamer encountered a general supporting library error.
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(375): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/deepstream-occupancy-analytics/bin/jetson/libnvds_msgconv.so: undefined symbol: nvds_msgapi_do_work
ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
Failed to start
App run failed
```

here is the config file that I used.
[test5_config_file_src_infer_tlt.txt](https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/files/5676847/test5_config_file_src_infer_tlt.txt)

**Comment by mjhuria** [comment]
Hello,
What deepstream version you are using?

**Comment by Ryan-ZL-Lin** [comment]
HI @mjhuria 
I'm using Deepstream 5.0

**Comment by mjhuria** [comment]
Just saw the config file. 
1. Please keep this line msg-broker-proto-lib=/opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_kafka_proto.so from original config file. Make sure you have libnvds_kafka_proto.so file in the given path 
2. Replace the libnvds_msgconv.so at deepstream-5.0/lib/libnvds_msgconv.so  from repo libnvds_msgconv.so  file
3. Make sure there is no error in 
bin/zookeeper-server-start.sh config/zookeeper.properties

bin/kafka-server-start.sh config/server.properties

Hope this helps!

**Comment by Ryan-ZL-Lin** [comment]
Hi @mjhuria 
I recoved the configuration from the original config file like this 
[test5_config_file_src_infer_tlt.txt](https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/files/5694057/test5_config_file_src_infer_tlt.txt)

I disabled sink0 and sink2 

[Sink1]
msg-broker-proto-lib=/opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_kafka_proto.so
msg-broker-conn-str=localhost;9092;quickstart-events

I also replaced the file (libnvds_msgconv.so) by using the one in the repo, here is the screenshot.
![libnvds_msgconv so](https://user-images.githubusercontent.com/33056320/102185435-e9333b80-3e65-11eb-9f86-9bf65f4ef80e.png)


however, I still got an error like this: 

> (deepstream-test5-analytics:23336): GLib-CRITICAL **: 23:42:02.609: g_strchug: assertion 'string != NULL' failed
> 
> (deepstream-test5-analytics:23336): GLib-CRITICAL **: 23:42:02.609: g_strchomp: assertion 'string != NULL' failed
> Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
> ** ERROR: <main:1088>: Failed to set pipeline to PAUSED
> Quitting
> ERROR from sink_sub_bin_sink1: Could not configure supporting library.
> Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(388): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin1/GstNvMsgBroker:sink_sub_bin_sink1:
> unable to connect to broker library
> ERROR from sink_sub_bin_sink1: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
> Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin1/GstNvMsgBroker:sink_sub_bin_sink1:
> Failed to start
> App run failed
>

**Comment by mjhuria** [comment]
Could you please check if the kafka server is running? 
What do you get when you run:
bin/kafka-server-start.sh config/server.properties
bin/kafka-topics.sh --list --zookeeper localhost:2181

**Comment by Ryan-ZL-Lin** [comment]
HI @mjhuria 
Here is what I got for the 2 commands above

**bin/kafka-server-start.sh config/server.properties**

> [2020-12-16 17:48:11,360] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@59b38691 (org.apache.zookeeper.ZooKeeper)
> [2020-12-16 17:48:11,398] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
> [2020-12-16 17:48:11,424] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:11,442] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
> [2020-12-16 17:48:11,468] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:11,488] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:12,596] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:12,603] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:13,711] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:13,717] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
> [2020-12-16 17:48:14,824] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)


**bin/kafka-topics.sh --list --zookeeper localhost:2181**

> Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
> 	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:262)
> 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:119)
> 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1865)
> 	at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:360)
> 	at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
> 	at kafka.admin.TopicCommand.main(TopicCommand.scala)
>

**Comment by Ryan-ZL-Lin** [comment]
Hi @mjhuria 
Thanks. Now I understand to keep these commands running at the background
**bin/zookeeper-server-start.sh config/zookeeper.properties 
bin/kafka-server-start.sh config/server.properties**

I also got a successful response from **bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server localhost:9092**

> Created topic quickstart-events.

I think the Kafka service is runnin properly now, when I run 
**sudo ./deepstream-test5-analytics -c config/test5_config_file_src_infer_tlt.txt**

I got an error that the source is not found

> ERROR from source: Resource not found.
> Debug info: gstfilesrc.c(533): gst_file_src_start (): /GstPipeline:pipeline/GstBin:multi_src_bin/GstBin:src_sub_bin0/GstURIDecodeBin:src_elem/GstFileSrc:source:
> No such file "/opt/nvidia/deepstream/deepstream-5.0/sources/apps/sample_apps/demo/out.mp4"
> 
>

It's the second time I download the Deepstream SDK, but I didn't find this video in the identified folder. Would you please let me know ehere I could get this video? I think the lines drawn in the video stream should be consistent with this file.

However, I tried to change the source to another video to see whether I could run the application properly and see the video stream. But I only got the following messages printed on the terminal and no video stream is displayed, is it normal?

> WARNING; playback mode used with URI [file:///opt/nvidia/deepstream/deepstream-5.0/samples/streams/sample_1080p_h264.mp4] not conforming to timestamp format; check README; using system-time
> Wed Dec 16 19:17:17 2020
> **PERF:  7.30 (7.28)	
> Wed Dec 16 19:17:22 2020
> **PERF:  7.19 (7.24)	
> Wed Dec 16 19:17:27 2020
> **PERF:  7.12 (7.15)

**Comment by mjhuria** [comment]
Hi Ryan,
Did you enable the sink0 or sink2? For video, No this is not an open source video. You can use any other test videos and can set the line configuration in config_nvdsanalytics.txt file.

**Comment by Ryan-ZL-Lin** [comment]
Thanks @mjhuria 
The problem is solved.

**Comment by gigwegbe** [comment]
Hello @Ryan-ZL-Lin,
Please can you share your final configuration. I followed your instructions above, however I still got the error: 
```
(deepstream-test5-analytics:26535): GLib-CRITICAL **: 16:05:50.010: g_strchug: assertion 'string != NULL' failed

(deepstream-test5-analytics:26535): GLib-CRITICAL **: 16:05:50.010: g_strchomp: assertion 'string != NULL' failed
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
** ERROR: <main:1088>: Failed to set pipeline to PAUSED
Quitting
ERROR from sink_sub_bin_sink2: Could not initialize supporting library.
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(359): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
unable to open shared library
ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
Failed to start
App run failed
```
--------------------------------------------------------------
Thanks

**Comment by BaoLee2589** [comment]
> Hello @Ryan-ZL-Lin,
> Please can you share your final configuration. I followed your instructions above, however I still got the error:
> 
> ```
> (deepstream-test5-analytics:26535): GLib-CRITICAL **: 16:05:50.010: g_strchug: assertion 'string != NULL' failed
> 
> (deepstream-test5-analytics:26535): GLib-CRITICAL **: 16:05:50.010: g_strchomp: assertion 'string != NULL' failed
> Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
> ** ERROR: <main:1088>: Failed to set pipeline to PAUSED
> Quitting
> ERROR from sink_sub_bin_sink2: Could not initialize supporting library.
> Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(359): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
> unable to open shared library
> ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
> Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
> Failed to start
> App run failed
> ```
> 
> Thanks

My   situation is the same as yours,if you solve it, could you help me? Thany you!

**Comment by NeethuES-intel** [comment]
@BaoLee2589 @gigwegbe @Ryan-ZL-Lin I am also having same issue. Let me know if you figure this out. Thanks.

**Comment by NeeSim** [comment]
@BaoLee2589 @gigwegbe @Ryan-ZL-Lin I am also getting similar error. Let me know if you solve this.
https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/issues/25#issuecomment-837553046

**Comment by NeeSim** [comment]
Kafka error is resolved. config/test5_config_file_src_infer_tlt.txt needs to be updated to point to right kafka library path.
Replace all 5.0 references to 5.1
