### ISSUE TITLE
Unable to run. Checked all factors but can not find the reason.

### ISSUE THREAD

**Issue by noobdevelop0512** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#51]
My platform is Nvidia Jetson Nano. Jetpack Version is 4.5.1. The CUDA version that comes with the system is 10.2. The Deepstream I installed is 5.1, It has been tested with official examples and installed successfully. The kafka I installed is 2.13-2.6.0 as the README in the repo. The quickstart event topic was successfully created.

I switched the libnvds_msgconv.so in the opt/nvidia/deepstream/deepstream-5.1/lib/ with the one in the repo cloned which is opt/nvidia/deepstream/deepstream-5.1/sources/apps/sample_apps/deepstream-occupancy-analytics/bin/jetson/.

I also changed all the '5.0' to '5.1' in the config/test5_config_file_src_infer_tlt.txt

The Build was successful.

In the Run phase, it says:

(deepstream-test5-analytics:24279): GLib-CRITICAL **: 17:24:37.349: g_strchug: assertion 'string != NULL' failed

(deepstream-test5-analytics:24279): GLib-CRITICAL **: 17:24:37.349: g_strchomp: assertion 'string != NULL' failed
** WARN: <create_pipeline:1141>: Num of Tiles less than number of sources, readjusting to 2 rows, 1 columns
Warning: 'input-dims' parameter has been deprecated. Use 'infer-dims' instead.
** ERROR: <main:1088>: Failed to set pipeline to PAUSED
Quitting
ERROR from sink_sub_bin_sink2: Could not initialize supporting library.
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(359): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
unable to open shared library
ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
Failed to start
App run failed

I have checked all the factors I know but still can not solve the problem. Can someone give me a hand?

**Comment by monjha** [comment]
Hi noobdeveloper,

The issue seems to be the kafka server. could you check if the kafka is running fine before starting the app?

**Comment by noobdevelop0512** [comment]
> Hi noobdeveloper,
> 
> The issue seems to be the kafka server. could you check if the kafka is running fine before starting the app?

**Comment by noobdevelop0512** [comment]
> Hi noobdeveloper,
> 
> The issue seems to be the kafka server. could you check if the kafka is running fine before starting the app?

Later I found the reason. The librdkafka was not installed correctly before the DS installation.
