### ISSUE TITLE
How to change the detection area

### ISSUE THREAD

**Issue by c7934597** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#7]
Hello, thank guys for sharing 

How to move the green line or increase the area for counting people crossing the line? 

I should adjust where program?

**Comment by mjhuria** [comment]
Hi,
you can change the area from here: https://github.com/NVIDIA-AI-IOT/deepstream-occupancy-analytics/blob/5c967c89db4405fc64b2bffe5942819ae076bcf2/config/config_nvdsanalytics.txt#L69
You need to update these coordinates as per your requirement.
Get more info on the parameters here: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvdsanalytics.html

**Comment by c7934597** [comment]
Thank you!
